### ISSUE TITLE
Add REUSE annotations for benchmarks in `collector/compile-benchmarks`

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rustc-perf#1939]
The code in `collector/compile-benchmarks` is now a submodule of `rust-lang/rust`, and included in source tarballs we distribute. We thus should annotate its licensing information so that it shows up in [the upcoming REUSE-powered licensing information](https://github.com/rust-lang/rust/issues/99414).

Once `rust-lang/rust` [upgrades to REUSE 4.x](https://github.com/rust-lang/rust/issues/127361) (which adds the new `REUSE.toml`), it should be possible to add a `REUSE.toml` in any sub-directory of `collector/compile-benchmark`, with a content like this:

```toml
version = 1

[[annotations]]
path = ["**"]
SPDX-FileCopyrightText = "Authorship / copyright line"
SPDX-License-Identifier = "SPDX-EXPRESSION"
```
